### ISSUE TITLE
HUGE Network and Memory issues using this plugin (and possible race condition)

### ISSUE THREAD

**Issue by jpalley** [iamladi/memcache_store_with_delete_matched#1]
This plugin caused many problems for us and a massive load on the memcache server.  Look at this before and after graph of memcache network bandwidth with this plugin:

http://developer.idapted.com/wp-content/uploads/2010/03/db1.lan-memcached_bytes-week.png

**Comment by iamladi** [comment]
Maybe you could try to fix it? The plugin was written by me a 2 years ago and I'm not using it anymore. Also the info you provided me would not help to solve the issue.
